{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.deploymentLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentLabel }}
    spec:
      containers:
      - name: {{ .Values.deploymentLabel }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        env:
        {{- if .Values.appname_enabled }}
        - name: SPRING_APPLICATION_NAME
          value: {{ .Values.appName }}
        {{- end }}
        {{- if .Values.profile_enabled }}
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_PROFILES_ACTIVE
        {{- end }}
        {{- if .Values.zipkin_enabled }}
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
        {{- end }}
        {{- if .Values.config_enabled }}
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_CONFIG_IMPORT
        {{- end }}
        {{- if .Values.eureka_enabled }}
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        {{- end }}

        {{- if .Values.carpark_db_enabled }}
        
        - name: POSTGRES_DB
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: CARPARK_DB

        - name: POSTGRES_USER
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: CARPARK_USER

        - name: POSTGRES_PASS
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: CARPARK_PASS

        {{- end }}


        {{- if .Values.account_db_enabled }}
        - name: SPRING_DATASOURCE_URL
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: ACCOUNTS_DATASOURCE_URL

        {{- end }}

        {{- if .Values.booking_db_enabled }}
        - name: SPRING_DATASOURCE_URL
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: BOOKINGS_DATASOURCE_URL
        {{- end }}

        {{- if .Values.carparketl_db_enabled }}
        - name: SPRING_DATASOURCE_URL
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: CARPARKETL_DATASOURCE_URL
        {{- end }}

        {{- if .Values.carparks_db_enabled }}
        - name: SPRING_DATASOURCE_URL
          valueFrom: 
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: CARPARKS_DATASOURCE_URL
        {{- end }}



{{- end -}}