deploymentName: accounts-deployment
deploymentLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: vtnhanhcmus/accounts
  tag: latest

containerPort: 8080

service:
  type: NodePort
  port: 8080
  targetPort: 8080

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
appname_enabled: true
account_db_enabled: true