deploymentName: bookings-deployment
deploymentLabel: bookings
appName: bookings

replicaCount: 1

image:
  repository: vtnhanhcmus/bookings
  tag: latest

containerPort: 10000

service:
  type: NodePort
  port: 10000
  targetPort: 10000

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
appname_enabled: true
booking_db_enabled: true