
deploymentName: carpark-db-deployment
deploymentLabel: carpark-db

replicaCount: 1

image:
  repository: kartoza/postgis
  tag: 15-3.3

containerPort: 5432

service:
  type: NodePort
  port: 5432
  targetPort: 5432

config_enabled: false
zipkin_enabled: false
profile_enabled: false
eureka_enabled: false
appname_enabled: false
carpark_db_enabled: true