apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vtnhanhcmus/ks8-helm.git'
    targetRevision: HEAD
    path: 'carpark-account'
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
